name: RL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - poetry=2.0.0
  - gymnasium=1.1.0
  - numpy=2.2.4
  - PyYAML=6.0.2
  - PyYAML=6.0.2
  - RL_algorithms=0.0.4
  - stable_baselines3=2.6.0
  - torch=2.6.0